# Generated by Django 4.0.3 on 2022-07-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_product_head0'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
